import { atom } from "jotai";

export type DialogType =
| 'login'
| 'register'
| 'forgotPassword'
| 'resetPassword'
| 'setPassword'
| 'account'
| 'deleteAccount'
| 'clearData'
| 'objectRemoverCompare'
| 'verifyEmail'
| 'logout'
| 'addCredit'
| 'loginToContinue'
| 'upgradeToPremiumVideo'
| 'upgradeToPremiumGIF'
| 'upgradeToPremiumMultiSwap'
| 'noCredits'
| 'noSufficientCredits'
| 'getMoreCredits'
| 'logout'
| 'manageFaces'
| 'noFaceDetected'
| 'videoDurationExceed'
| 'contactUs'
| 'manageSubscription'
| 'cancelSubscription'
| 'feedback'
| 'chromaStudio'
| 'manageFaces'

export const dialogAtom = atom<DialogType[] >([]);
